CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY,name VARCHAR(40) NOT NULL,age SMALLINT CHECK(age IS NULL OR(age>=18 AND age<=120)),country VARCHAR(80),language VARCHAR(80),interests TEXT[] NOT NULL DEFAULT '{}',avatar TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS matches (id UUID PRIMARY KEY,user_a UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,user_b UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,status VARCHAR(20) NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),ended_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY,match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,text VARCHAR(2000) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reports (id BIGSERIAL PRIMARY KEY,reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,reported_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,match_id UUID REFERENCES matches(id) ON DELETE SET NULL,reason VARCHAR(500) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS blocks (blocker_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,blocked_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(blocker_id,blocked_id));
CREATE INDEX IF NOT EXISTS messages_match_idx ON messages(match_id,created_at);CREATE INDEX IF NOT EXISTS users_last_seen_idx ON users(last_seen);

CREATE TABLE IF NOT EXISTS agent_runs (
  id BIGSERIAL PRIMARY KEY,
  run_type VARCHAR(40) NOT NULL,
  status VARCHAR(20) NOT NULL,
  summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS content_ideas (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(160) NOT NULL UNIQUE,
  keyword VARCHAR(200),
  audience VARCHAR(120),
  intent VARCHAR(80),
  rationale TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'idea',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS content_drafts (
  id BIGSERIAL PRIMARY KEY,
  idea_id BIGINT REFERENCES content_ideas(id) ON DELETE SET NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(160) NOT NULL UNIQUE,
  description VARCHAR(320),
  body TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS agent_runs_created_idx ON agent_runs(created_at);
CREATE INDEX IF NOT EXISTS content_ideas_status_idx ON content_ideas(status);

CREATE TABLE IF NOT EXISTS gift_events (id BIGSERIAL PRIMARY KEY,match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,receiver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,gift VARCHAR(80) NOT NULL,required_minutes SMALLINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS gift_events_match_idx ON gift_events(match_id,created_at);

CREATE TABLE IF NOT EXISTS google_accounts (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  google_sub VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(320),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS friendships (
  requester_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addressee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(requester_id,addressee_id),
  CHECK(requester_id<>addressee_id)
);
CREATE INDEX IF NOT EXISTS friendships_addressee_idx ON friendships(addressee_id,status);

CREATE TABLE IF NOT EXISTS google_accounts (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, google_sub VARCHAR(255) NOT NULL UNIQUE, email VARCHAR(320), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS friendships (requester_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, addressee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(requester_id,addressee_id), CHECK(requester_id<>addressee_id));
CREATE INDEX IF NOT EXISTS friendships_addressee_idx ON friendships(addressee_id,status);