require('dotenv').config();
const express=require('express'),http=require('http'),path=require('path'),fs=require('fs'),helmet=require('helmet'),cors=require('cors'),rateLimit=require('express-rate-limit'),jwt=require('jsonwebtoken');
const {Pool}=require('pg'),{Server}=require('socket.io'),{v4:uuidv4}=require('uuid');
const {runGrowthAgent,draftIdea,SITE_URL,MODEL}=require('./agent');
const PORT=Number(process.env.PORT||10000),JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME';
if(JWT_SECRET==='CHANGE_ME')console.warn('Set JWT_SECRET before production.');
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL) console.error('DATABASE_URL is missing. Talkly needs the Supabase/Postgres connection string in production.');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10});
const app=express(),server=http.createServer(app),origin=process.env.ALLOWED_ORIGIN||true,io=new Server(server,{cors:{origin:true,credentials:true},transports:['polling','websocket'],pingTimeout:20000,pingInterval:25000});
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'},contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'","'unsafe-inline'"],scriptSrcAttr:["'unsafe-inline'"],styleSrc:["'self'","'unsafe-inline'","https://fonts.googleapis.com"],fontSrc:["'self'","https://fonts.gstatic.com"],imgSrc:["'self'","data:","https://images.unsplash.com"],connectSrc:["'self'","ws:","wss:"]}}}));app.use(cors({origin,credentials:true}));app.use(express.json({limit:'20kb'}));app.use(rateLimit({windowMs:60000,limit:120,standardHeaders:true,legacyHeaders:false}));app.use(express.static(__dirname));
const queue=[],sockets=new Map(),db=(sql,p=[])=>pool.query(sql,p),clean=(v,n)=>String(v??'').trim().slice(0,n);
const auth=(req,res,next)=>{try{const h=req.headers.authorization||'';req.user=jwt.verify(h.startsWith('Bearer ')?h.slice(7):'',JWT_SECRET);next()}catch{res.status(401).json({error:'Unauthorized'})}};
const socketAuth=(s,n)=>{try{s.user=jwt.verify(s.handshake.auth?.token||'',JWT_SECRET);n()}catch{n(new Error('unauthorized'))}};
async function init(){for(const q of fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8').split(';').map(x=>x.trim()).filter(Boolean))await db(q)}
function agentAdmin(req,res,next){const key=process.env.AGENT_ADMIN_KEY;if(!key)return res.status(503).json({error:'AGENT_ADMIN_KEY is not configured'});if(req.headers['x-agent-key']!==key)return res.status(401).json({error:'Invalid agent key'});next()}
app.get('/api/agent/dashboard',agentAdmin,async(req,res)=>{try{const stats=(await db(\`SELECT (SELECT COUNT(*) AS n FROM users) AS users,(SELECT COUNT(*) FROM matches) AS matches,(SELECT COUNT(*) FROM messages) AS messages,(SELECT COUNT(*) FROM users WHERE created_at>=NOW()-INTERVAL '7 days') AS new_users_7d,(SELECT COUNT(*) FROM matches WHERE created_at>=NOW()-INTERVAL '7 days') AS matches_7d,(SELECT COUNT(*) FROM messages WHERE created_at>=NOW()-INTERVAL '7 days') AS messages_7d\`)).rows[0];const ideas=(await db('SELECT id,title,slug,keyword,audience,intent,rationale,status,created_at FROM content_ideas ORDER BY created_at DESC LIMIT 20')).rows;res.json({site:SITE_URL,model:MODEL,stats,ideas})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/agent/run',agentAdmin,async(req,res)=>{try{res.json(await runGrowthAgent(db))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/agent/draft',agentAdmin,async(req,res)=>{try{const id=Number(req.body?.ideaId);const q=await db('SELECT id,title,slug,keyword,audience,intent,rationale FROM content_ideas WHERE id=$1',[id]);if(!q.rowCount)return res.status(404).json({error:'Idea not found'});const d=await draftIdea(q.rows[0]);const slug=String(q.rows[0].slug).slice(0,150);const saved=await db('INSERT INTO content_drafts(idea_id,title,slug,description,body,status) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(slug) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,body=EXCLUDED.body RETURNING id,title,slug,description,body,status',[id,String(d.title||q.rows[0].title).slice(0,200),slug,String(d.description||'').slice(0,320),String(d.body||''),'draft']);res.json(saved.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/health',async(q,r)=>{try{await db('SELECT 1');r.json({ok:true,service:'talkly',database:'connected'})}catch(e){r.status(503).json({ok:false,service:'talkly',database:'not_connected',error:process.env.NODE_ENV==='production'?'Database configuration error':e.message})}});
app.post('/api/session',async(req,res)=>{if(!DATABASE_URL)return res.status(503).json({error:'Database is not configured. Add DATABASE_URL in the hosting environment.'});const id=uuidv4(),name=clean(req.body?.name||'Guest',40)||'Guest',avatar=clean(req.body?.avatar||'',500)||null;const x=await db('INSERT INTO users(id,name,avatar) VALUES($1,$2,$3) RETURNING id,name,age,country,language,interests,avatar',[id,name,avatar]);res.json({token:jwt.sign({sub:id},JWT_SECRET,{expiresIn:'30d'}),user:x.rows[0]})});
app.get('/api/me',auth,async(req,res)=>{const x=await db('SELECT id,name,age,country,language,interests,avatar FROM users WHERE id=$1',[req.user.sub]);if(!x.rowCount)return res.status(404).json({error:'Not found'});res.json(x.rows[0])});
app.patch('/api/me',auth,async(req,res)=>{const name=clean(req.body?.name,40)||'Guest',age=req.body?.age==null?null:Number(req.body.age),country=clean(req.body?.country,80)||null,language=clean(req.body?.language,80)||null,interests=Array.isArray(req.body?.interests)?req.body.interests.map(x=>clean(x,30)).filter(Boolean).slice(0,10):[],avatar=clean(req.body?.avatar,500)||null;if(age!==null&&(!Number.isInteger(age)||age<18||age>120))return res.status(400).json({error:'Invalid age'});const x=await db('UPDATE users SET name=$1,age=$2,country=$3,language=$4,interests=$5,avatar=$6,last_seen=NOW() WHERE id=$7 RETURNING id,name,age,country,language,interests,avatar',[name,age,country,language,interests,avatar,req.user.sub]);res.json(x.rows[0])});
app.post('/api/report',auth,async(req,res)=>{const who=clean(req.body?.reportedUserId,60),reason=clean(req.body?.reason,500)||'Other';if(!who||who===req.user.sub)return res.status(400).json({error:'Invalid report'});await db('INSERT INTO reports(reporter_id,reported_user_id,match_id,reason) VALUES($1,$2,$3,$4)',[req.user.sub,who,req.body?.matchId||null,reason]);res.json({ok:true})});
app.post('/api/block',auth,async(req,res)=>{const who=clean(req.body?.blockedUserId,60);if(!who||who===req.user.sub)return res.status(400).json({error:'Invalid block'});await db('INSERT INTO blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.sub,who]);res.json({ok:true})});
async function blocked(a,b){const x=await db('SELECT 1 FROM blocks WHERE(blocker_id=$1 AND blocked_id=$2) OR(blocker_id=$2 AND blocked_id=$1) LIMIT 1',[a,b]);return !!x.rowCount}
async function match(s,f={}){const uid=s.user.sub;if(queue.some(x=>x.uid===uid))return;let i=-1;for(let n=0;n<queue.length;n++){const c=queue[n];if(c.uid===uid||c.busy)continue;if(f.language&&c.f.language&&c.f.language!==f.language)continue;if(f.country&&c.f.country&&c.f.country!==f.country)continue;if(f.interests?.length&&c.f.interests?.length&&!f.interests.some(x=>c.f.interests.includes(x)))continue;if(await blocked(uid,c.uid))continue;c.busy=true;i=n;break}if(i<0){queue.push({uid,s,f,busy:false});s.emit('queue:waiting');return}const c=queue.splice(i,1)[0],id=uuidv4();await db('INSERT INTO matches(id,user_a,user_b) VALUES($1,$2,$3)',[id,uid,c.uid]);const u=await db('SELECT id,name,age,country,language,interests,avatar FROM users WHERE id=ANY($1::uuid[])',[[uid,c.uid]]),by=Object.fromEntries(u.rows.map(x=>[x.id,x]));s.current={id,partner:c.uid};c.s.current={id,partner:uid};s.emit('match:found',{matchId:id,partner:by[c.uid]});c.s.emit('match:found',{matchId:id,partner:by[uid]})}
io.use(socketAuth);
io.on('connection',s=>{const uid=s.user.sub;sockets.set(uid,s);db('UPDATE users SET last_seen=NOW() WHERE id=$1',[uid]).catch(()=>{});s.on('queue:join',f=>{match(s,{language:clean(f?.language,80)||null,country:clean(f?.country,80)||null,interests:Array.isArray(f?.interests)?f.interests.map(x=>clean(x,30)).slice(0,10):[]}).catch(e=>{console.error('Match error:',e.message);s.emit('match:error',{message:'Matching is temporarily unavailable. Please try again.'})})});s.on('queue:cancel',()=>{for(let i=queue.length-1;i>=0;i--)if(queue[i].uid===uid)queue.splice(i,1)});s.on('chat:message',async d=>{const t=clean(d?.text,2000),m=s.current;if(!m||!t)return;const ok=await db("SELECT 1 FROM matches WHERE id=$1 AND status='active' AND(user_a=$2 OR user_b=$2)",[m.id,uid]);if(!ok.rowCount)return;const x=await db('INSERT INTO messages(match_id,sender_id,text) VALUES($1,$2,$3) RETURNING id,text,created_at',[m.id,uid,t]),p={id:x.rows[0].id,text:x.rows[0].text,createdAt:x.rows[0].created_at,senderId:uid};s.emit('chat:message',p);sockets.get(m.partner)?.emit('chat:message',p)});s.on('match:leave',async()=>{const m=s.current;if(!m)return;await db("UPDATE matches SET status='ended',ended_at=NOW() WHERE id=$1 AND status='active'",[m.id]).catch(()=>{});const o=sockets.get(m.partner);if(o){o.emit('match:left');o.current=null}s.current=null});for(const e of ['voice:offer','voice:answer','voice:ice','voice:end'])s.on(e,d=>{const o=sockets.get(s.current?.partner);if(o)o.emit(e,d)});s.on('disconnect',async()=>{for(let i=queue.length-1;i>=0;i--)if(queue[i].uid===uid)queue.splice(i,1);const m=s.current;if(m){await db("UPDATE matches SET status='ended',ended_at=NOW() WHERE id=$1 AND status='active'",[m.id]).catch(()=>{});sockets.get(m.partner)?.emit('match:left')}sockets.delete(uid)})});
app.get('/agent', (req,res)=>res.sendFile(path.join(__dirname,'agent.html')));
app.get('/*splat',(req,res,next)=>req.path.startsWith('/api/')||req.path.startsWith('/socket.io/')?next():res.sendFile(path.join(__dirname,'index.html')));
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('Talkly running on '+PORT))).catch(e=>{console.error('Database initialization failed:',e.message);process.exit(1)});
